packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@emotion/react': ^11.11.3
  '@emotion/styled': ^11.11.0
  '@mui/material': ^5.15.10
  '@qlj/screenshot-compare': ^0.0.5
  '@types/pixelmatch': ^5.2.6
  '@types/pngjs': ^6.0.4
  '@types/prompts': ^2.4.9
  '@types/react': ^18.2.55
  '@types/react-dom': ^18.2.19
  '@typescript-eslint/eslint-plugin': ^6.21.0
  '@typescript-eslint/parser': ^6.21.0
  '@vitejs/plugin-react': ^4.2.1
  '@webcontainer/api': 1.5.1-internal.9
  chalk: ^5.4.1
  commander: ^11.1.0
  eslint-plugin-react-hooks: ^4.6.0
  eslint-plugin-react-refresh: ^0.4.5
  pixelmatch: ^5.3.0
  playwright: ^1.51.0
  pngjs: ^7.0.0
  prompts: ^2.4.2
  puppeteer: ^22.0.0
  react: ^18.2.0
  react-dom: ^18.2.0
catalogs:
  cli:
    '@antfu/eslint-config': ^4.8.1
    '@antfu/ni': ^23.3.1
    bumpp: ^10.0.3
    eslint: ^8.56.0
    lint-staged: ^15.4.3
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.2.2
    unbuild: ^3.5.0
    vite: ^5.1.0
  testing:
    '@types/js-yaml': ^4.0.9
    js-yaml: ^4.1.0
    vitest-package-exports: ^0.1.1
    vitest: ^3.0.8
  types:
    '@types/node': ^22.13.9
  utils:
    '@antfu/utils': ^9.1.0
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
